export const paths = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  users: "/users",
  lands: "/lands",
  buildings: "/buildings",
  units: "/units",
  clients: "/clients",
  contractors: "/contractors",
  suppliers: "/suppliers",
  workItems: "/work-items",
  materialPurchases: "/material-purchases",
  unitSales: "/unit-sales",
  paymentSchedules: "/payment-schedules",
  payablePayments: "/payable-payments",
  financialTransactions: "/financial-transactions",
  reports: "/reports",
  incomeExpense: "/reports",
  auditLogs: "/audit-logs",
  auditLogDetails: (id) => `/audit-logs/${id}`,
};
